#!/usr/bin/env bash

read -p "Enter bucket name: " bucket_name
echo "Bucket name: '${bucket_name}'"

job_name="ml_job_$(date +%Y_%m_%d___%H_%M_%S)"

echo "Job name: ${job_name}"

job_dir=gs://${bucket_name}/${job_name}
echo "Job dir: ${job_dir}"

region=us-east1
echo "Region: ${region}"



gcloud ai-platform jobs submit training ${job_name} --job-dir ${job_dir} \
  --python-version 3.5   \
  --runtime-version 1.9  \
  --module-name trainer.train   `# train.py` \
  --package-path ./trainer      \
  --region ${region}     \
  --scale-tier BASIC_GPU \
  --  `# Next, provide the params for train.py` \
  --weights_stage "${job_dir}/weights_stage_exported.h5" \
  --weights_final "${job_dir}/weights_final_exported.h5" \
    `# input files: ` \
  --anchors_file "gs://${bucket_name}/tiny_yolo_anchors.txt" \
  --annotation_path "gs://${bucket_name}/2012_train.txt" \
  --classes_path "gs://${bucket_name}/voc_classes.txt"


