#!/usr/bin/env bash

read -p "Enter bucket name: " bucket_name
echo "Bucket name: '${bucket_name}'"

job_name="ml_job_$(date +%Y%m%d_%H%M%S)"

echo "Job name: ${job_name}"

job_dir=gs://${bucket_name}/${job_name}
echo "Job dir: ${job_dir}"

gcloud ai-platform local train \
 --python-version 3.5   \
 --job-dir ${job_dir}   \
 --module-name yolo3.train   `# train.py` \
 --package-path yolo3/  \
 --distributed \
 --  `# Next, provide the params to train.py` \
 --weights_stage "${job_dir}/weights_stage_exported.h5" \
 --weights_final "${job_dir}/weights_final_exported.h5" \
 --anchors_file "model_data/tiny_yolo_anchors.txt"
