#!/usr/bin/env bash

read -p "Enter bucket name: " bucket_name
echo "Bucket name: '${bucket_name}'"

job_name="ml_job_$(date +%Y%m%d_%H%M%S)"

echo "Job name: ${job_name}"

job_dir=gs://${bucket_name}/${job_name}
echo "Job dir: ${job_dir}"

gcloud ai-platform local train \
 --job-dir ${job_dir} \
 --module-name trainer/train   `# train.py` \
 --package-path ./trainer \
 --distributed \
 --  `# Next, provide the params to train.py` \
 --weights_stage "${job_dir}/weights_stage_exported.h5" \
 --weights_final "${job_dir}/weights_final_exported.h5" \
 --anchors_file "model_data/tiny_yolo_anchors.txt"
